# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classiscoming', '0002_instituicao_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classiscoming.Curso')),
            ],
        ),
    ]
