# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('classiscoming', '0005_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
