# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classiscoming', '0006_auto_20160804_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classiscoming.Instituicao')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classiscoming.Perfil')),
            ],
        ),
    ]
